[package]
name = "prender"
version = "0.1.0"
authors = ["David Cristofaro <david@dtcristo.com>"]
edition = "2018"

[dependencies]
bevy = { version = "0.5", default_features = false }
bevy_pixels = "0.1"
line_drawing = "0.8"
rand = "0.8"
