[package]
name = "prender"
version = "0.1.0"
authors = ["David Cristofaro <david@dtcristo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.bevy]
version = "0.5"
default-features = false
features = ["bevy_winit"]

[dependencies]
bevy_pixels = { git = "https://github.com/dtcristo/bevy_pixels", branch = "main" }
line_drawing = "0.8.0"
rand = "0.8.0"
