[package]
name = "sector"
description = "Sector/portal renderer with Bevy"
version = "0.1.0"
authors = ["David Cristofaro <david@dtcristo.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/dtcristo/sector"
publish = false

[dependencies]
bevy = { version = "0.18.1", default-features = false, features = ["bevy_scene"] }
earcutr = "0.5"
geo = "0.32"
geo-polygonize-core = "0.33"
geo-types = "0.7"
lazy_static = "1"
palette = "0.6"
ron = "0.12.0"
serde = { version = "1", features = ["derive"] }
thiserror = "2"

# sector(bin) deps
bevy_pixels = { path = "../bevy_pixels", version = "0.16.0", optional = true }
image = { version = "0.24", optional = true }

# sector_edit(bin) deps
bevy_egui = { version = "0.39.1", optional = true }
egui_plot = { version = "0.34.0", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"

[features]
sector = [
    "bevy/bevy_asset",
    "bevy/file_watcher",
    "bevy_pixels",
    "image"
]
sector_edit = [
    "bevy/bevy_asset",
    "bevy/bevy_winit",
    "bevy/ui_bevy_render",
    "bevy_egui",
    "egui_plot"
]

[[bin]]
name = "sector"
required-features = ["sector"]

[[bin]]
name = "sector_edit"
required-features = ["sector_edit"]

[[bin]]
name = "sector_validate"
