[package]
name = "sector"
version = "0.1.0"
authors = ["David Cristofaro <david@dtcristo.com>"]
edition = "2021"

[dependencies]
bevy = { version = "0.9", default_features = false }
bevy_pixels = { path = "../bevy_pixels", version = "0.6" }
bevy_render = "0.9"
lazy_static = "1.4"
rust_bresenham = "0.1"
image = "0.24"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
