[package]
name = "sector"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
bevy = { workspace = true, features = ["bevy_asset", "bevy_scene", "filesystem_watcher"] }
bevy_pixels.workspace = true
image.workspace = true
lazy_static.workspace = true
palette.workspace = true
rmp-serde.workspace = true
rust_bresenham.workspace = true
sector_core.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook.workspace = true
