[package]
name = "sector_edit"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
bevy = { workspace = true, features = ["bevy_asset", "bevy_scene", "bevy_winit"] }
bevy_egui.workspace = true
palette.workspace = true
rmp-serde.workspace = true
sector_core.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook.workspace = true
